config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :items
  resources :categories
  resources :orders do
    resources :order_items do
      get :increment, on: :member
      get :decrement, on: :member
    end
  end

  patch 'admin/order/:id/cancel' => 'admin/orders#cancel',   as: :cancel_order
  patch 'admin/pay/:id/pay'      => 'admin/orders#pay',      as: :pay_order
  patch 'admin/pay/:id/complete' => 'admin/orders#complete', as: :complete_order

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get     '/cart'             => 'carts#show',              as: :cart
  get     '/add_to_cart'      => 'carts#add_to_cart_view',  as: :add_to_cart

  get     '/cart/edit'        => 'carts#edit',              as: :edit_cart
  patch   '/cart'             => 'carts#update'
  put     '/cart'             => 'carts#update'
  post    '/cart/items'       => 'cart_items#create',       as: :cart_items
  delete  '/cart/items'       => 'cart_items#destroy',      as: :cart_items_destroy

  put     '/admin/retire/item'      => 'admin/retire_item#update'

  get     '/order_items/new'  => 'order_items#new',         as: :new_order_item
  post    '/order_items'      => 'order_items#create',      as: :order_items

  get     '/about_us'          => 'about_us#index' 

  namespace :admin do
    resources :admin
    resources :items
    resources :categories
    resources :orders do
      resources :order_items do
        get :increment, on: :member
        get :decrement, on: :member
      end
    end
  end

  match '/admin_dashboard',  to: 'admin/admin#show',  via: 'get'
end

app/models/order.rb
class Order < ActiveRecord::Base
  class Status
    PAID      = "paid"
    CANCELLED = "cancelled"
    COMPLETED = "completed"
    ORDERED   = "ordered"

    ALL       = [PAID, CANCELLED, COMPLETED, ORDERED]
  end

  def self.status_counts()
    result = Order.group(:order_status).count  # select status, count(*) from Order group by status
    Status::ALL.each {|key| result[key] ||= 0}
    result
  end

  def self.all_count
    Order.count
  end

  has_many    :order_items
  has_many    :items, through: :order_items
  belongs_to  :user

  validates :user_id,          presence: true
  validates :order_total,      presence: true
  validates :order_type,       presence: true
  validates :delivery_address, presence: true, if: :delivery?
  # validates :order_status,     presence: true
  # validates :order_status,     presence: true, inclusion: {in: Status::ALL}

  def delivery?
    order_type == "delivery"
  end

  def cancelled?
    order_status == "cancelled"
  end

  def ordered?
    order_status == "ordered"
  end

  def paid?
    order_status == "paid"
  end

  def complete?
    order_status == 'completed'
  end

  def item_quantity(item_id)
    self.items.select { |i| i.id == item_id }.count
  end

  def subtotal(item_id)
    self.item_quantity(item_id) * self.items.find(item_id).price_pie
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action	:set_order,   only: [:show, :edit, :update, :destroy, :cancel, :pay, :complete]
  before_action :authorize?,  only: [:index, :edit, :update, :destroy, :cancel, :pay, :complete]

  def index
    @status_counts = Order.status_counts
    @all_count     = Order.all.count
    if params[:filter]
      @orders = Order.where(order_status: params[:filter])
    else
      @orders = Order.all
    end
  end

  def show
  end

  def cancel
    @order.order_status = "cancelled"
    @order.save
    redirect_to admin_order_path(@order)
  end

  def pay
    @order.order_status = "paid"
    @order.save
    redirect_to admin_order_path(@order)
  end

  def complete
    @order.order_status = 'completed'
    @order.save
    redirect_to admin_order_path(@order)
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:user_id,
                                    :order_total,
                                    :order_type,
                                    :delivery_address,
                                    :order_status
                                    )
    end

    def authorize?
      redirect_to "https://www.youtube.com/watch?v=Jvk7faxsxkQ" unless current_user.role == "admin"
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def new
    @order = Order.new
  end

  def show
    @order
  end

  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save!
        @cart.items.each do |item|
          @order.order_items.create!(item_id: item.id, order_id: @order.id)
        end
        cart_destroy
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
      else
        render :new
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @order.destroy

    flash.notice= 'Order was successfully destroyed.'

    redirect_to admin_orders_url
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:user_id,
                                    :order_total,
                                    :order_type,
                                    :delivery_address,
                                    :order_status
                                    )
    end
end

app/views/admin/orders/index.html.erb
<%= render :partial => "shared/header" %>
<div class="content-wrapper formStyle">
  <h1>Order Management</h1>
  <h3>Order Status Counts:</h3>
  <table class='table'>
    <thead>
      <tr>
        <th>All Orders:</th>
        <th>Paid:</th>
        <th>Cancelled:</th>
        <th>Completed:</th>
        <th>Ordered:</th>
      </tr>
    </thead>

    <tbody>
      <td><%= link_to 'See All Orders', admin_orders_path %>(<%= @all_count %>)</td>
      <td><%= link_to 'See Paid Orders', admin_orders_path(filter: 'paid') %>(<%= @status_counts[Order::Status::PAID] %>)</td>
      <td><%= link_to 'See Cancelled Orders', admin_orders_path(filter: 'cancelled') %>(<%= @status_counts[Order::Status::CANCELLED] %>)</td>
      <td><%= link_to 'See Completed Orders', admin_orders_path(filter: 'completed') %>(<%= @status_counts[Order::Status::COMPLETED] %>)</td>
      <td><%= link_to 'See Ordered/Pending Orders', admin_orders_path(filter: 'ordered') %>(<%= @status_counts[Order::Status::ORDERED] %>)</td>
    </tbody>
  </table>

  <table class='table'>
    <thead>
      <tr>
        <th>Order ID:</th>
        <th>User ID:</th>
        <th>Order Total:</th>
        <th>Order Type:</th>
        <th>Delivery Address:</th>
        <th>Order Status:</th>
        <th>Options:</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, admin_order_path(order) %></td>
        <td><%= order.user_id %></td>
        <td><%= order.order_total %></td>
        <td><%= order.order_type.upcase %></td>
        <td><%= order.delivery_address %></td>
        <td><%= order.order_status.upcase %></td>
        <td>
          <%= link_to "Delete", order, method: :delete, data: { confirm: 'Are you sure?'} %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/show.html.erb
<%= render :partial => "shared/header" %>
<div class="content-wrapper formStyle"
  <h1>Order Details:</h1>

  <h3>Customer Info:</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Customer Name:</th>
        <th>Customer Email:</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @order.user.full_name %></td>
        <td><%= @order.user.email %></td>
      </tr>
    </tbody>
  </table>

  <h3>Order Overview:</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Order Date and Time:</th>
        <th>Order Total:</th>
        <th>Order Type:</th>
        <th>Order Status:</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @order.created_at.to_formatted_s(:long) %></td>
        <td>$<%= @order.order_total %></td>
        <td><%= @order.order_type.upcase %></td>
        <td>
          <%= @order.order_status.upcase %><br/>
          Last updated at: <%= @order.updated_at.to_formatted_s(:long)%>
        </td>
      </tr>
    </tbody>
  </table>

  <h3>Order Items:</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Item:</th>
        <th>Price:</th>
        <th>Quantity:</th>
        <th>Subtotal:</th>
      </tr>
    </thead>

    <tbody>
      <% unique_order_items = @order.order_items.to_a.uniq { |order_item| order_item.item_id } %>
      <% unique_order_items.each do |order_item| %>
        <tr>
          <td><strong><%= link_to "#{order_item.item.title}", item_path(order_item.item) %></strong></td>
          <td><%= order_item.item.price_pie %></td>
          <% item_id = order_item.item_id %>
          <td>
            <%= quantity = @order.order_items.select { |order_item| order_item.item_id == item_id }.count%>
            <%= link_to "+", increment_order_order_item_path(@order, order_item) %>
            <%= link_to "-", decrement_order_order_item_path(@order, order_item) %>
          </td>
          <td><%= quantity * order_item.item.price_pie %></td>
        </tr>
      <% end %>
      </tr>
    </tbody>
  </table>

  <div>
  <% if @order.ordered? %>
    <%= link_to 'Cancel Order', cancel_order_path(@order), method: :patch %> |
  <% end %>
  <% if @order.ordered? %>
    <%= link_to 'Mark As Paid', pay_order_path(@order), method: :patch %> |
  <% end %>
  <% if @order.paid? %>
    <%= link_to 'Cancel Order', cancel_order_path(@order), method: :patch %> |
  <% end %>
  <% if @order.paid? %>
    <%= link_to 'Mark As Completed', complete_order_path(@order), method: :patch %> |
  <% end %>

  <%= link_to 'Back to Orders Index', admin_orders_path %>
  </div>
</div>