config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :items
  resources :categories
  resources :orders do
    resources :order_items do
      get :increment, on: :member
      get :decrement, on: :member
    end
  end

  patch 'admin/order/:id/cancel' => 'admin/orders#cancel',   as: :cancel_order
  patch 'admin/pay/:id/pay'      => 'admin/orders#pay',      as: :pay_order
  patch 'admin/pay/:id/complete' => 'admin/orders#complete', as: :complete_order

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get     '/cart'             => 'carts#show',              as: :cart
  get     '/add_to_cart'      => 'carts#add_to_cart_view',  as: :add_to_cart

  get     '/cart/edit'        => 'carts#edit',              as: :edit_cart
  patch   '/cart'             => 'carts#update'
  put     '/cart'             => 'carts#update'
  post    '/cart/items'       => 'cart_items#create',       as: :cart_items
  delete  '/cart/items'       => 'cart_items#destroy',      as: :cart_items_destroy

  put     '/admin/retire/item'      => 'admin/retire_item#update'

  get     '/order_items/new'  => 'order_items#new',         as: :new_order_item
  post    '/order_items'      => 'order_items#create',      as: :order_items

  get     '/about_us'          => 'about_us#index' 

  namespace :admin do
    resources :admin
    resources :items
    resources :categories
    resources :orders do
      resources :order_items do
        get :increment, on: :member
        get :decrement, on: :member
      end
    end
  end

  match '/admin_dashboard',  to: 'admin/admin#show',  via: 'get'
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p class="pull-right"></p>
  <p>&copy; Dangerously Delicious Pies &middot;</p>
  <p>13339 H Street Washington DC 20002</p>
  <p>202.398.7437</p>
</footer>

app/views/shared/_header.html.erb
<div class="navbar-wrapper">
  <div class="container">

    <div class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Dangerously. Delicious. Pies', root_path, class: "navbar-brand" %>

        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'All Items', items_path %></li>
                <li class="divider"></li>
                <li class="dropdown-header">View Items by Category</li>
                <% Category.all.each do |c| %>
                  <li><%= link_to c.name, category_path(c) %></li>
                <% end %>
              </ul>
            </li>
            <li><%= link_to 'Who We Are', about_us_path %></li>
            <li><%= link_to 'Cart', cart_path %></li>
            <li>
              <% if @cart_count != 0 %>
                <%= link_to "(#{@cart_count})", cart_path %>
              <% else %>
                <%= "" %>
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Your Account <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Your Order History', current_user %></li>
                <% if current_user != nil && current_user.role == 'admin' %>
                  <li>
                    <%= link_to 'Admin Dashboard', admin_dashboard_path %>
                  </li>
                <% end %>
                <% if signed_in? %>
                  <li class= 'align_menu'>
                    <%= link_to 'Sign Out', signout_path, method: 'delete' %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to 'Sign in', signin_path %>
                  </li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

  </div>
</div>