config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :items
  resources :categories
  resources :orders do
    resources :order_items do
      get :increment, on: :member
      get :decrement, on: :member
    end
  end

  patch 'admin/order/:id/cancel' => 'admin/orders#cancel',   as: :cancel_order
  patch 'admin/pay/:id/pay'      => 'admin/orders#pay',      as: :pay_order
  patch 'admin/pay/:id/complete' => 'admin/orders#complete', as: :complete_order

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get     '/cart'             => 'carts#show',              as: :cart
  get     '/add_to_cart'      => 'carts#add_to_cart_view',  as: :add_to_cart

  get     '/cart/edit'        => 'carts#edit',              as: :edit_cart
  patch   '/cart'             => 'carts#update'
  put     '/cart'             => 'carts#update'
  post    '/cart/items'       => 'cart_items#create',       as: :cart_items
  delete  '/cart/items'       => 'cart_items#destroy',      as: :cart_items_destroy

  put     '/admin/retire/item'      => 'admin/retire_item#update'

  get     '/order_items/new'  => 'order_items#new',         as: :new_order_item
  post    '/order_items'      => 'order_items#create',      as: :order_items

  get     '/about_us'          => 'about_us#index' 

  namespace :admin do
    resources :admin
    resources :items
    resources :categories
    resources :orders do
      resources :order_items do
        get :increment, on: :member
        get :decrement, on: :member
      end
    end
  end

  match '/admin_dashboard',  to: 'admin/admin#show',  via: 'get'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	# This holds our items until checkout
	# How can we make this hold our items
	# How can we just add one item to the cart
	# So we click on an item
	# It adds that item to our cart
	# and it saves it
	has_many :cart_items
	has_many :items, through: :cart_items

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@cart = cart
	end

	def update
	end

  def edit
  	@item = item
  	Cart.create(@item.id, @item.title, @item.description,  @item.price_pie)
  end

	def add_to_cart_view
		item = Item.find(params[:item_id])
		cart.items << item
		redirect_to items_path
	end
end

app/views/carts/index.html.erb
<%= render :partial => "shared/header" %>
<% @cart.items.each do |item| %>
	<%= item.title %>
<% end %>

app/views/carts/show.html.erb
<%= render :partial => "shared/header" %>
<h1>Order Details:</h1>
<div class="content-wrapper formStyle">
  <table class='table'>
    <thead>
      <tr>
        <th>Pie:</th>
        <th>Price:</th>
        <th>Quantity:</th>
        <th>Item Total:</th>
      </tr>
    </thead>

    <tbody>
      <% unique_cart_items = @cart.cart_items.to_a.uniq { |cart_item| cart_item.item_id } %>
      <% unique_cart_items.each do |cart_item| %>
        <tr>
          <td><%= link_to cart_item.item.title, item_path(cart_item.item) %></td>
          <td><%= cart_item.item.price_pie %></td>
          <% item_id = cart_item.item_id %>
          <td>
            <%= quantity =  @cart.cart_items.select { |cart_item| cart_item.item_id == item_id }.count%>
            <span class='item_quantity_changer'><%= link_to '+', cart_items_path(item_id: item_id), method: :post %></span>
            <span class='item_quantity_changer'><%= link_to '-', cart_items_path(item_id: item_id), method: :delete %></span>
            <br/>

          </td>
          <td>
            <%= quantity * cart_item.item.price_pie %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <%= form_tag orders_path, method: :post do %>
      <% order = Order.new %>
      <%= hidden_field_tag 'order[user_id]', current_user.try(:id) || 1 %>

      <div class='form-group'>
        <%= label_tag 'Order Total:' %>
        <%= @total_price = @cart.cart_items.reduce(0) { |total, cart_item| total += cart_item.item.price_pie } %>
        <%= hidden_field_tag 'order[order_total]', (sprintf '%0.2f', @total_price) %>
      </div>

      <div class='form-group'>
        <%= label_tag 'Order Type:' %>
        <%= select_tag 'order[order_type]', '<option>Pickup</option><option>Delivery</option>'.html_safe %><br/>
        <%= label_tag 'Delivery Address:' %>
        <%= text_field_tag 'order[delivery_address]' %>
        <%= hidden_field_tag 'order[order_status]', 'ordered' %>
      </div>

      <div class='actions'>
        <% if current_user != nil && @total_price != 0 %>
          <%= submit_tag 'Checkout', class: "btn btn-default" %>
        <% elsif @total_price == 0 %>
          <%= link_to 'Keep Shopping', items_path, class: "btn btn-default" %>
        <% elsif %>
          <%= link_to 'Sign In', signin_path, class: "btn btn-default" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>