config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :items
  resources :categories
  resources :orders do
    resources :order_items do
      get :increment, on: :member
      get :decrement, on: :member
    end
  end

  patch 'admin/order/:id/cancel' => 'admin/orders#cancel',   as: :cancel_order
  patch 'admin/pay/:id/pay'      => 'admin/orders#pay',      as: :pay_order
  patch 'admin/pay/:id/complete' => 'admin/orders#complete', as: :complete_order

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get     '/cart'             => 'carts#show',              as: :cart
  get     '/add_to_cart'      => 'carts#add_to_cart_view',  as: :add_to_cart

  get     '/cart/edit'        => 'carts#edit',              as: :edit_cart
  patch   '/cart'             => 'carts#update'
  put     '/cart'             => 'carts#update'
  post    '/cart/items'       => 'cart_items#create',       as: :cart_items
  delete  '/cart/items'       => 'cart_items#destroy',      as: :cart_items_destroy

  put     '/admin/retire/item'      => 'admin/retire_item#update'

  get     '/order_items/new'  => 'order_items#new',         as: :new_order_item
  post    '/order_items'      => 'order_items#create',      as: :order_items

  get     '/about_us'          => 'about_us#index' 

  namespace :admin do
    resources :admin
    resources :items
    resources :categories
    resources :orders do
      resources :order_items do
        get :increment, on: :member
        get :decrement, on: :member
      end
    end
  end

  match '/admin_dashboard',  to: 'admin/admin#show',  via: 'get'
end

app/views/admin/admin/show.html.erb
<%= render :partial => "shared/header" %>
<h1>Welcome to the Adminstrative Dashboard</h1>

<div class="content-wrapper formStyle">
  <table class="table">
    <thead>
      <tr>
        <th><h3><center>Menu Management</center></h3></th>
        <th><h3><center>Order/Customer Management</center></h3></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <h4><center><%= link_to 'Menu Item Management', admin_items_path %></center></h4><br/>
          <h4><center><%= link_to 'Menu Category Managment', admin_categories_path %></center></h4>
        </td>
        <td>
          <h4><center><%= link_to 'Order Management', admin_orders_path %></center></h4><br/>
        </td>
      </tr>
    </tbody>
  </table>
</div>